name: 'Synopsys Polaris SAST Check'
description: 'Polaris SAST runner'
inputs:
  server_url:
    description: 'URL of the polaris server instance'
    required: true
  access_token:
    description: 'Access token for accessing the polaris server instance'
    required: true
  total_issues:
    description: 'A count of total issues'
    required: false
    default: '0'
  new_issues: 
    description: 'A count of new issues'
    required: false
    default: '0'
  cli_scan_json_file:
    description: 'The cli-scan.json file location'
    required: false
    default: '.synopsys/polaris/cli-scan.json'
  command_opts:
    required: false
    description: 'Additional command line options'
    default: '' 
    
runs:
  using: "composite"
  steps: 
  - name: Downloading polaris_cli
    run: wget -q ${{ inputs.server_url}}/api/tools/polaris_cli-linux64.zip
    shell: bash
  - name: Extracting polaris_cli-linux64.zip to tmp
    run: unzip -j polaris_cli-linux64.zip -d /tmp
    shell: bash
  - name: Running Scan 
    run: |
        export POLARIS_ACCESS_TOKEN=${{ secrets.POLARIS_ACCESS_TOKEN_CSPROD }}
        export POLARIS_SERVER_URL=${{ secrets.POLARIS_SERVER_URL_CSPROD }}
        /tmp/polaris ${{ inputs.command_opts }} analyze -w --coverity-ignore-capture-failure
    shell: bash
  - run: ${{ github.action_path}}/polaris-scan-result-check.py ${{ inputs.cli_scan_json_file }} ${{ inputs.total_issues }} ${{ inputs.new_issues }}
    shell: bash
